### PR TITLE
Act on keypress(block = FALSE) on Windows

### PR DESCRIPTION
**Pull request by weshinsley**
Implement use of `(block = FALSE)` on Windows.
See https://github.com/gaborcsardi/keypress/issues/9

### CODE REVIEW

**Review by gaborcsardi — COMMENTED** [review]
Thanks! Sorry for the long wait. I don't quite get how this works, though.

I think `ReadConsoleInputA` is supposed to block, no? But apparently it does not, at least not initially...

OTOH this PR quits for this first event, whatever that is, which is probably not the right thing to do, because it always gives me `"0"`.

**Comment by weshinsley** [comment]
Yes, you're right... playing with this some more, ReadConsoleInputA seems a bit weird - it doesn't block when I call it - but I am now wondering whether it's fast enough that pushing "enter" to execute `k <- kepress(block = FALSE);` is enough to register as a keypress, so ReadConsoleInputA returns a result quickly...

I will read the Console API a bit more and see if I can get some better behaviour...

**Comment by weshinsley** [comment]
I think this is on the way now - not sure quite how you write tests for this non-blocking behaviour - but this is my hack... It returns "none" instead of 0 if there's no key.
```
x <- 0
while (TRUE) {
  Sys.sleep(0.1)
  kp <- keypress(block = FALSE)
  cat(paste(x, kp, "     \r"))
  x <- (x + 1) %% 10
}
```

If block = TRUE, then I have to push a key to get any change. If block = FALSE, then the counter spins and I can push keys (or not) while it does so.

See how this looks - it's a fairly "modest" change in the end. Happy to do more on it if there are things you'd like.

**Comment by gaborcsardi** [comment]
Thanks! 

My issue with this approach is that it is easy to end up without terminal echo, e.g. if an error happens in your package / script. I think it is fine to have low level on/off functions, maybe as internal functions, but it would be nicer to offer a `with_` style function that automatically restores echo, so you can write this:

```r
with_no_echo(
  fucntion_that_needs_to_avoid_echo()
)
```

Btw. Do you actually need the C API, ot you added that for completeness?

**Comment by gaborcsardi** [comment]
I am sorry for the long wait and thanks again!

**Pull request merged**
