### PR TITLE
Fix characters leaking into unix terminal in non-blocking mode

### PR DESCRIPTION
**Pull request by weshinsley**
This fixes the problem on unix/mac (bash terminals), described in issue #10

### CODE REVIEW

**Comment by gaborcsardi** [comment]
Thanks! 

My issue with this approach is that it is easy to end up without terminal echo, e.g. if an error happens in your package / script. I think it is fine to have low level on/off functions, maybe as internal functions, but it would be nicer to offer a `with_` style function that automatically restores echo, so you can write this:

```r
with_no_echo(
  fucntion_that_needs_to_avoid_echo()
)
```

Btw. Do you actually need the C API, ot you added that for completeness?

**Comment by weshinsley** [comment]
Well... Perhaps the best thing is to point you to my rather unusual [use case](https://github.com/weshinsley/cactus.purge) ! (That uses my fork of keypress - it needs both PR #8 and PR #11 to work). 

Yes - losing the echo is a bit of a risk in this sort of code if it breaks! Good idea to pull the on.exit into a `with_no_echo`, rather than it being in the user code. I'll convert this one to the with() form - and then wrap the whole of my code in one!

**Comment by gaborcsardi** [comment]
Thanks again, and sorry for the very long wait! I trimmed down the C API a bit, hopefully that's ok for your use case.

**Comment by weshinsley** [comment]
Thanks Gabor! I'll try it out...

**Pull request merged**
